/*
 * data.h
 *
 *  Created on: Jun 15, 2020
 *      Author: Alex
 */
#ifndef DATA_H_
#define DATA_H_

#define CARD_NAME "Dashboard"
#define PROGRAM_NAME "dash"
#define VERSION "1.0.4"

#define SLAVE_OWN_ADDRESS_BASE 0x35

#define MIN_CH_NO 1
#define CRT_IN_CH_NO 8
#define LED_CH_NO 8

#define CRT_SCALE 100

#define COUNTER_SIZE 4
#define ANALOG_VAL_SIZE 2

#define OPTO_CH_NR 16
#define OPTO_CH_NO OPTO_CH_NR
#define COUNTER_SIZE 4

#define ADC_RAW_VAL_SIZE	2
#define ANALOG_VAL_SIZE 2

#define OD_CH_NO 4
#define V_IN_CH_NO 8
#define R_IN_CH_NO 2


#define CALIBRATION_KEY 0xaa
#define RESET_CALIBRATION_KEY	0x55
#define ZERO_CURRENT_KEY 0x11

#define WDT_RESET_SIGNATURE     0xca
#define WDT_RESET_COUNT_SIGNATURE    0xbe

#define VOLT_TO_MILIVOLT 1000
#define MILIAMPER_TO_MICROAMPER 1000

enum
{
	CALIB_IN_PROGRESS = 0,
	CALIB_DONE,
	CALIB_ERROR,
};

enum
{
	CALIB_NOTHING = 0,
	CALIB_CRT_IN_CH1,
};

enum
{
	I2C_MEM_OD,
	I2C_MEM_OD_SET,
	I2C_MEM_OD_CLR,


	I2C_MEM_OPTO,//16 bits for opto inputs
	I2C_MEM_VIN_START = I2C_MEM_OPTO + 2,
	I2C_MEM_RIN_START = I2C_MEM_VIN_START + V_IN_CH_NO * ANALOG_VAL_SIZE,
	I2C_MEM_OD_PWM_START = I2C_MEM_RIN_START + R_IN_CH_NO * ADC_RAW_VAL_SIZE,
	I2C_MEM_BACKLIGHT_PWM = I2C_MEM_OD_PWM_START + OD_CH_NO * ANALOG_VAL_SIZE,


	I2C_MEM_DIAG_3V3_MV = I2C_MEM_BACKLIGHT_PWM +ANALOG_VAL_SIZE,
	I2C_MEM_DIAG_CPU_TEMP = I2C_MEM_DIAG_3V3_MV + ANALOG_VAL_SIZE,
	I2C_MEM_OPTO_COUNT_ENABLE = I2C_MEM_DIAG_CPU_TEMP + ANALOG_VAL_SIZE,

	I2C_MEM_OPTO_CNT_RST_ADD = I2C_MEM_OPTO_COUNT_ENABLE + 2,

	I2C_MEM_OPTO_EDGE_COUNT_ADD,

	I2C_MEM_CALIB_VALUE = I2C_MEM_OPTO_EDGE_COUNT_ADD + OPTO_CH_NR * COUNTER_SIZE,
	I2C_MEM_CALIB_CHANNEL = I2C_MEM_CALIB_VALUE + 4, //Thermo [1..4]; 4-20_IN[5/6] // calibration not functional yet
	I2C_MEM_CALIB_KEY, //set calib point -> 0xaa; reset calibration on the channel -> 0x55
	I2C_MEM_CALIB_STATUS,

	I2C_MEM_WDT_RESET_ADD,
	I2C_MEM_WDT_INTERVAL_SET_ADD,
	I2C_MEM_WDT_INTERVAL_GET_ADD = I2C_MEM_WDT_INTERVAL_SET_ADD + 2,
	I2C_MEM_WDT_INIT_INTERVAL_SET_ADD = I2C_MEM_WDT_INTERVAL_GET_ADD + 2,
	I2C_MEM_WDT_INIT_INTERVAL_GET_ADD = I2C_MEM_WDT_INIT_INTERVAL_SET_ADD + 2,
	I2C_MEM_WDT_RESET_COUNT_ADD = I2C_MEM_WDT_INIT_INTERVAL_GET_ADD + 2,
	I2C_MEM_WDT_CLEAR_RESET_COUNT_ADD = I2C_MEM_WDT_RESET_COUNT_ADD + 2,
	I2C_MEM_WDT_POWER_OFF_INTERVAL_SET_ADD,
	I2C_MEM_WDT_POWER_OFF_INTERVAL_GET_ADD = I2C_MEM_WDT_POWER_OFF_INTERVAL_SET_ADD
		+ 4,
	I2C_MEM_DIAG_VCC_MV = I2C_MEM_WDT_POWER_OFF_INTERVAL_GET_ADD + 4,
	I2C_MEM_DIN_POWER_CTRL_CH_ADD = I2C_MEM_DIAG_VCC_MV + 2,
	I2C_MEM_DIN_DEBOUNCE_ON_MS_ADD = I2C_MEM_DIN_POWER_CTRL_CH_ADD + 1,
	I2C_MEM_DIN_DEBOUNCE_OFF_MS_ADD = I2C_MEM_DIN_DEBOUNCE_ON_MS_ADD + 2,
	I2C_MEM_POWER_OFF_DELAY_S_ADD = I2C_MEM_DIN_DEBOUNCE_OFF_MS_ADD + 2,
	I2C_MEM_POWER_PRESENT = I2C_MEM_POWER_OFF_DELAY_S_ADD + 2,
	I2C_MEM_DISPLAY_AUTO_ON_INTERVAL_S_ADD = I2C_MEM_POWER_PRESENT + 1,
	I2C_MEM_DISPLAY_FADE_INCREMENT = I2C_MEM_DISPLAY_AUTO_ON_INTERVAL_S_ADD + 2,
	I2C_MEM_OD1_PWM_DEFAULT = I2C_MEM_DISPLAY_FADE_INCREMENT + 2,
	I2C_MEM_OD2_PWM_DEFAULT = I2C_MEM_OD1_PWM_DEFAULT + 2,
	I2C_MEM_OD3_PWM_DEFAULT = I2C_MEM_OD2_PWM_DEFAULT + 2,
	I2C_MEM_OD4_PWM_DEFAULT = I2C_MEM_OD3_PWM_DEFAULT + 2,


	I2C_MEM_REVISION_HW_MAJOR_ADD = 251,
	I2C_MEM_REVISION_HW_MINOR_ADD,
	I2C_MEM_REVISION_MAJOR_ADD,
	I2C_MEM_REVISION_MINOR_ADD,

	SLAVE_BUFF_SIZE = 255,
};

#define I2C_MODBUS_SETINGS I2C_MODBUS_SETINGS_ADD
#define ERROR -1
#define ERR ERROR
#define OK 0
#define ARG_CNT_ERR -2
#define ARG_RANGE_ERROR -3
#define ARG_RANGE_ERR ARG_RANGE_ERROR
#define IO_ERROR -4

#define STR_(x) #x
#define STR(x) STR_(x)
#define MASK_1 1
#define MASK_2 3
#define MASK_3 7
#define MASK_4 15
#define MASK_5 31
#define MASK_6 63
#define MASK_7 127
#define MASK_(x) MASK_##x
#define MASK(x) MASK_(x)

typedef enum {
	OFF,
	ON,
	STATE_COUNT,
} State;

#endif /* DATA_H_ */
